// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTsoaw1keK3XjfGaiizVnZQIbdMv68RpA',
    appId: '1:529884891306:web:c7ba45efdf6b53ea5a68d3',
    messagingSenderId: '529884891306',
    projectId: 'shoppingmall-flutter-jjw',
    authDomain: 'shoppingmall-flutter-jjw.firebaseapp.com',
    storageBucket: 'shoppingmall-flutter-jjw.appspot.com',
    measurementId: 'G-JHN8R0F1SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBKT0xr3sjaJDyiTOF1CuzpuHcBzn86O8',
    appId: '1:529884891306:android:3badc16f19fcfdb15a68d3',
    messagingSenderId: '529884891306',
    projectId: 'shoppingmall-flutter-jjw',
    storageBucket: 'shoppingmall-flutter-jjw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgNBc4HQrSXaAoIVDBHatq2z8Dsy5k4r8',
    appId: '1:529884891306:ios:afbcebf63f04ce725a68d3',
    messagingSenderId: '529884891306',
    projectId: 'shoppingmall-flutter-jjw',
    storageBucket: 'shoppingmall-flutter-jjw.appspot.com',
    iosClientId: '529884891306-e53d28b6qmn163uqni3lgoip00ipqf94.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingmallFlutter',
  );
}
